name: 'RcppDeepState'
author: 'Fabrizio Sandri'
description: 'This Action runs RcppDeepState in any Rcpp-based projects hosted on GitHub'
inputs:
  location:  
    description: 'Location of the package if not in the root of the repository'
    required: false
    default: '/'
  seed:  
    description: 'Seed used for deterministic fuzz testing and reproduce the analysis results'
    required: false
    default: '-1'
  time_limit:
    description: "Fuzzing phase's duration in seconds"
    required: false
    default: '2'
  max_inputs:
    description: 'Number of inputs generated in the fuzzing phase to analyze'
    required: false
    default: '3'


runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v2 
      with:
        repository: FabrizioSandri/RcppDeepState-action
        path: RcppDeepState-action

    - name: Analyze the package with RcppDeepState 
      uses: ./RcppDeepState-action/docker
      with:
        location: ${{ inputs.location }}
        seed: ${{ inputs.seed }}
        time_limit: ${{ inputs.time_limit }}
        max_inputs: ${{ inputs.max_inputs }}
