name: 'RcppDeepState'
author: 'Fabrizio Sandri'
description: 'This Action runs RcppDeepState inside a Docker container'
inputs:
  fail_ci_if_error:
    description: 'Specify if CI pipeline should fail when RcppDeepState finds errors'
    require: false
    default: 'false'
  location:  
    description: 'Location of the package if not in the root of the repository'
    required: false
    default: '/'
  seed:  
    description: 'Seed used for deterministic fuzz testing and reproduce the analysis results'
    required: false
    default: '-1'
  time_limit_seconds:
    description: "Fuzzing phase's duration in seconds"
    required: false
    default: '2'
  max_inputs:
    description: 'Number of inputs generated in the fuzzing phase to analyze'
    required: false
    default: '3'
  verbose:
    description: 'Enables verbose logging of RcppDeepState'
    require: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.fail_ci_if_error }}
    - ${{ inputs.location }}
    - ${{ inputs.seed }}
    - ${{ inputs.time_limit_seconds }}
    - ${{ inputs.max_inputs }}
    - ${{ inputs.verbose }}
