on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
      
name: RcppDeepState

jobs:
  RcppDeepState:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:      
      - uses: actions/checkout@v2 

      - uses: actions/checkout@v2 # checkout 'FabrizioSandri/RcppDeepState' containing the 'testSAN' package
        with:
          repository: FabrizioSandri/RcppDeepState
          path: RcppDeepState

      - name: Analyze the package with RcppDeepState  # run RccpDeepState on 'testSAN'
        uses: ./
        with:
          location: /RcppDeepState/inst/testpkgs/testSAN
          fail_ci_if_error: 'false'
          comment: 'true'
          