on:
  pull_request:
    branches: 
      - '*'

name: "Check testSAN package"

jobs:
  RcppDeepState:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:      
      - uses: actions/checkout@v2 

      - name: Switch to test image
        run: |
          sed -i "s/fabriziosandri\/rcppdeepstate:latest/fabriziosandri\/rcppdeepstate:devel/g" action.yml
        shell: bash

      - name: Analyze the package with RcppDeepState  # run RccpDeepState on 'testSAN'
        uses: ./
        with:
          location: /tests/testSAN
          fail_ci_if_error: 'false'
          comment: 'true'
          