on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

name: check-bugfree-package
jobs:
  RcppDeepState:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:      
      - uses: actions/checkout@v2 
      
      - name: Analyze the package with RcppDeepState  # run RccpDeepState on 'TestPackage'
        uses: ./
        with:
          location: /tests/TestPackage
          time_limit: 5
          max_inputs: 3
